package com.neuq.info.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Auto_Id
     *
     * @mbggenerated
     */
    private Integer autoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Order_Id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Restaurant_Name
     *
     * @mbggenerated
     */
    private String restaurantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Restaurant_Location
     *
     * @mbggenerated
     */
    private String restaurantLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Restaurant_People
     *
     * @mbggenerated
     */
    private Integer restaurantPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Queue_Type
     *
     * @mbggenerated
     */
    private Integer queueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Start_Time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Arrive_Time
     *
     * @mbggenerated
     */
    private Date arriveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Contact_Name
     *
     * @mbggenerated
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Phone_Num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Fee
     *
     * @mbggenerated
     */
    private Double fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Extra_Fee
     *
     * @mbggenerated
     */
    private Double extraFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Customer_Id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Provider_Id
     *
     * @mbggenerated
     */
    private Long providerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Order_Status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Update_Time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Order.Create_Time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_Order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Auto_Id
     *
     * @return the value of T_Order.Auto_Id
     *
     * @mbggenerated
     */
    public Integer getAutoId() {
        return autoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Auto_Id
     *
     * @param autoId the value for T_Order.Auto_Id
     *
     * @mbggenerated
     */
    public void setAutoId(Integer autoId) {
        this.autoId = autoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Order_Id
     *
     * @return the value of T_Order.Order_Id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Order_Id
     *
     * @param orderId the value for T_Order.Order_Id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Restaurant_Name
     *
     * @return the value of T_Order.Restaurant_Name
     *
     * @mbggenerated
     */
    public String getRestaurantName() {
        return restaurantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Restaurant_Name
     *
     * @param restaurantName the value for T_Order.Restaurant_Name
     *
     * @mbggenerated
     */
    public void setRestaurantName(String restaurantName) {
        this.restaurantName = restaurantName == null ? null : restaurantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Restaurant_Location
     *
     * @return the value of T_Order.Restaurant_Location
     *
     * @mbggenerated
     */
    public String getRestaurantLocation() {
        return restaurantLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Restaurant_Location
     *
     * @param restaurantLocation the value for T_Order.Restaurant_Location
     *
     * @mbggenerated
     */
    public void setRestaurantLocation(String restaurantLocation) {
        this.restaurantLocation = restaurantLocation == null ? null : restaurantLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Longitude
     *
     * @return the value of T_Order.Longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Longitude
     *
     * @param longitude the value for T_Order.Longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Latitude
     *
     * @return the value of T_Order.Latitude
     *
     * @mbggenerated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Latitude
     *
     * @param latitude the value for T_Order.Latitude
     *
     * @mbggenerated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Restaurant_People
     *
     * @return the value of T_Order.Restaurant_People
     *
     * @mbggenerated
     */
    public Integer getRestaurantPeople() {
        return restaurantPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Restaurant_People
     *
     * @param restaurantPeople the value for T_Order.Restaurant_People
     *
     * @mbggenerated
     */
    public void setRestaurantPeople(Integer restaurantPeople) {
        this.restaurantPeople = restaurantPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Queue_Type
     *
     * @return the value of T_Order.Queue_Type
     *
     * @mbggenerated
     */
    public Integer getQueueType() {
        return queueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Queue_Type
     *
     * @param queueType the value for T_Order.Queue_Type
     *
     * @mbggenerated
     */
    public void setQueueType(Integer queueType) {
        this.queueType = queueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Start_Time
     *
     * @return the value of T_Order.Start_Time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Start_Time
     *
     * @param startTime the value for T_Order.Start_Time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Arrive_Time
     *
     * @return the value of T_Order.Arrive_Time
     *
     * @mbggenerated
     */
    public Date getArriveTime() {
        return arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Arrive_Time
     *
     * @param arriveTime the value for T_Order.Arrive_Time
     *
     * @mbggenerated
     */
    public void setArriveTime(Date arriveTime) {
        this.arriveTime = arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Contact_Name
     *
     * @return the value of T_Order.Contact_Name
     *
     * @mbggenerated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Contact_Name
     *
     * @param contactName the value for T_Order.Contact_Name
     *
     * @mbggenerated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Phone_Num
     *
     * @return the value of T_Order.Phone_Num
     *
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Phone_Num
     *
     * @param phoneNum the value for T_Order.Phone_Num
     *
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Gender
     *
     * @return the value of T_Order.Gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Gender
     *
     * @param gender the value for T_Order.Gender
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Comment
     *
     * @return the value of T_Order.Comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Comment
     *
     * @param comment the value for T_Order.Comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Fee
     *
     * @return the value of T_Order.Fee
     *
     * @mbggenerated
     */
    public Double getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Fee
     *
     * @param fee the value for T_Order.Fee
     *
     * @mbggenerated
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Extra_Fee
     *
     * @return the value of T_Order.Extra_Fee
     *
     * @mbggenerated
     */
    public Double getExtraFee() {
        return extraFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Extra_Fee
     *
     * @param extraFee the value for T_Order.Extra_Fee
     *
     * @mbggenerated
     */
    public void setExtraFee(Double extraFee) {
        this.extraFee = extraFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Customer_Id
     *
     * @return the value of T_Order.Customer_Id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Customer_Id
     *
     * @param customerId the value for T_Order.Customer_Id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Provider_Id
     *
     * @return the value of T_Order.Provider_Id
     *
     * @mbggenerated
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Provider_Id
     *
     * @param providerId the value for T_Order.Provider_Id
     *
     * @mbggenerated
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Order_Status
     *
     * @return the value of T_Order.Order_Status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Order_Status
     *
     * @param orderStatus the value for T_Order.Order_Status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Update_Time
     *
     * @return the value of T_Order.Update_Time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Update_Time
     *
     * @param updateTime the value for T_Order.Update_Time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Order.Create_Time
     *
     * @return the value of T_Order.Create_Time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Order.Create_Time
     *
     * @param createTime the value for T_Order.Create_Time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Order
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Order other = (Order) that;
        return (this.getAutoId() == null ? other.getAutoId() == null : this.getAutoId().equals(other.getAutoId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getRestaurantName() == null ? other.getRestaurantName() == null : this.getRestaurantName().equals(other.getRestaurantName()))
            && (this.getRestaurantLocation() == null ? other.getRestaurantLocation() == null : this.getRestaurantLocation().equals(other.getRestaurantLocation()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getRestaurantPeople() == null ? other.getRestaurantPeople() == null : this.getRestaurantPeople().equals(other.getRestaurantPeople()))
            && (this.getQueueType() == null ? other.getQueueType() == null : this.getQueueType().equals(other.getQueueType()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getArriveTime() == null ? other.getArriveTime() == null : this.getArriveTime().equals(other.getArriveTime()))
            && (this.getContactName() == null ? other.getContactName() == null : this.getContactName().equals(other.getContactName()))
            && (this.getPhoneNum() == null ? other.getPhoneNum() == null : this.getPhoneNum().equals(other.getPhoneNum()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getFee() == null ? other.getFee() == null : this.getFee().equals(other.getFee()))
            && (this.getExtraFee() == null ? other.getExtraFee() == null : this.getExtraFee().equals(other.getExtraFee()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getProviderId() == null ? other.getProviderId() == null : this.getProviderId().equals(other.getProviderId()))
            && (this.getOrderStatus() == null ? other.getOrderStatus() == null : this.getOrderStatus().equals(other.getOrderStatus()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Order
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAutoId() == null) ? 0 : getAutoId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getRestaurantName() == null) ? 0 : getRestaurantName().hashCode());
        result = prime * result + ((getRestaurantLocation() == null) ? 0 : getRestaurantLocation().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getRestaurantPeople() == null) ? 0 : getRestaurantPeople().hashCode());
        result = prime * result + ((getQueueType() == null) ? 0 : getQueueType().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getArriveTime() == null) ? 0 : getArriveTime().hashCode());
        result = prime * result + ((getContactName() == null) ? 0 : getContactName().hashCode());
        result = prime * result + ((getPhoneNum() == null) ? 0 : getPhoneNum().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getFee() == null) ? 0 : getFee().hashCode());
        result = prime * result + ((getExtraFee() == null) ? 0 : getExtraFee().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getProviderId() == null) ? 0 : getProviderId().hashCode());
        result = prime * result + ((getOrderStatus() == null) ? 0 : getOrderStatus().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", autoId=").append(autoId);
        sb.append(", orderId=").append(orderId);
        sb.append(", restaurantName=").append(restaurantName);
        sb.append(", restaurantLocation=").append(restaurantLocation);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", restaurantPeople=").append(restaurantPeople);
        sb.append(", queueType=").append(queueType);
        sb.append(", startTime=").append(startTime);
        sb.append(", arriveTime=").append(arriveTime);
        sb.append(", contactName=").append(contactName);
        sb.append(", phoneNum=").append(phoneNum);
        sb.append(", gender=").append(gender);
        sb.append(", comment=").append(comment);
        sb.append(", fee=").append(fee);
        sb.append(", extraFee=").append(extraFee);
        sb.append(", customerId=").append(customerId);
        sb.append(", providerId=").append(providerId);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}