package com.neuq.info.dao;

import com.neuq.info.entity.Order;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;

public interface OrderDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer autoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Order
     *
     * @mbggenerated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer autoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Order record);

    int updateByOrderId(Order record);

    Order selectByOrderId(String orderId);

    int deleteByOrderId(String orderId);

    //根据经纬度查找订单
    List<Order> findNeighPositionByCondition(HashMap hashMap);


    //列出玩家的订单  如果是客户，根据客户的id state 按照创建的时间逆序排列  帮客 也是一样的
    List<Order> listOrderByCondition(HashMap hashmap);

  //  @Param("minlng") BigDecimal minlng, @Param("maxlng")BigDecimal maxlng,
  //  @Param("minlat") BigDecimal minlat, @Param("maxlat") BigDecimal maxlat

}