package com.neuq.info.dao;

import com.neuq.info.entity.CustomerUser;
import com.neuq.info.entity.ProviderUser;

public interface ProviderUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ProviderUser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ProviderUser
     *
     * @mbggenerated
     */
    int insertSelective(ProviderUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ProviderUser
     *
     * @mbggenerated
     */
    ProviderUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ProviderUser
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProviderUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ProviderUser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProviderUser record);

    /**
     * 新增user
     *
     * @param record
     * @return
     */
    int insert(ProviderUser record);


    /**
     * 根据用户id查询user
     *
     * @param userId
     * @return
     */
    ProviderUser queryUserById(long userId);

    /**
     * 根据openid查询user
     *
     * @param openid
     * @return
     */
    ProviderUser queryUserByOpenId(String openid);

    /**
     * 根据unionid查询user
     *
     * @param unionId
     * @return
     */
    ProviderUser queryUserByUnionId(String unionId);

    /**
     * 更新用户信息根据openId
     *
     * @param record
     * @return
     */
    int updateUser(ProviderUser record);
}