package com.neuq.info.dao;

import com.neuq.info.entity.User;

public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    /**
     * 新增user
     *
     * @param user
     * @return
     */
    int insertUser(User user);

    /**
     * 根据用户id查询user
     *
     * @param userId
     * @return
     */
    User queryUserByUserId(long userId);

    /**
     * 根据openid查询user
     *
     * @param openid
     * @return
     */
    User queryUserByOpenId(String openid);

    /**
     * 查询所有数量
     *
     * @return
     */
    int queryAllUserCount();

    /**
     * 更新用户信息根据openId
     *
     * @param user
     * @return
     */
    int updateUser(User user);

}